# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Matt Kersley | Peterborough Web Designer and Developer"
email: mkersley@gmail.com
description: Peterborough based web designer and developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mattkersley.com" # the base hostname & protocol for your site
permalink: /:categories/:title

#social stuff
site_avatar: "https://avatars2.githubusercontent.com/u/635655?v=3&s=144"
twitter_username: kersley
github_username:  mattkersley

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
